apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "webapp.fullname" . }}-index
  labels:
    {{- include "webapp.labels" . | nindent 4 }}
data:
  index.html: |
    <!doctype html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Helm + Jenkins Capstone</title>
      <style>
        body { font-family: -apple-system, system-ui, Segoe UI, Roboto, Arial, sans-serif; margin: 3rem; }
        .tag { padding: .2rem .5rem; border: 1px solid #ddd; border-radius: 8px; display: inline-block; margin-right: .5rem; }
      </style>
    </head>
    <body>
      <h1>Deployed with Helm 🚀</h1>
      <p>Served by <strong>nginx</strong> on Kubernetes (Minikube).</p>
      <p class="tag">Release: {{ .Release.Name }}</p>
      <p class="tag">Namespace: {{ .Release.Namespace }}</p>
      <p class="tag">Chart: {{ .Chart.Name }}-{{ .Chart.Version }}</p>
      <p>Edit this text, push, and let Jenkins redeploy.</p>
    </body>
    </html>
